#!/usr/bin/env bash

pushd $(dirname $0) > /dev/null
pluginsdir="./plugins/"

echo '{ "version": 1 }'
echo '['
echo '[]'

jsonstring=""
while true
do
	for i in $(cat "$pluginsdir/.order")
	do
		jsonstring="${jsonstring}$(${pluginsdir}$i)"
	done

	echo -e ",[${jsonstring%,}]"
	jsonstring=""
	sleep 5
done
