#!/usr/bin/env bash

source "./lib/bash/jsonify"
pluginname="battery"
threshold=20.0
chlevel=$(acpitool -b | cut -f 2 -d ',' | sed -e 's/[ %]//g')

if acpitool -b | grep -oe "Charging\|Unknown\|Charged" > /dev/null
then
	plugintext="⚡ ${chlevel}%"
	plugincolor="#00FF00"
else
	plugintext="∞ ${chlevel}%"
	if [ "$(echo "${chlevel}<${threshold}" | bc -l)" -eq 1 ]
	then
		plugincolor="#FF0000"
	else
		plugincolor="#CCCC00"
	fi
fi

jsonify "$pluginname" "$plugintext" "$plugincolor"
